INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Welcome to the jungle','guns n roses','appetite for destruction','1988','Classic Rock');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Smooth Criminal','Michael Jackson','Bad','1988','Pop');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Billie Jean','Michael Jackson','Thriller','1982','Pop');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Enter Sandman','Metallica','The Black Album','1991','Heavy Metal');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Take on Me','A-Ha','Hunting High and Low','1985','Synthpop, New Wave');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Another Brick in the Wall','Pink Floyd','The Wall','1979','Progressive Rock');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Voyage Voyage','Desireless','François','1989','Synthpop');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('With or Without You','U2','The Joshua Tree','1987','Rock');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Girls Just Want to Have Fun','Cyndi Lauper','She is So Unusual','1983','Pop');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Eye of the Tiger','Survivor','Eye of the Tiger','1982','Rock');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Africa','Toto','Toto IV','1982','Rock');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Like a Prayer','Madonna','Like a Prayer','1989','Pop');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Livin on a Prayer','Bon Jovi','Slippery When Wet','1986','Rock');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Wake Me Up Before You Go-Go','Wham!','Make It Big','1984','Pop');
INSERT INTO TB_MUSICA(TITULO,ARTISTA,ALBUM,ANO,GENERO) VALUES ('Sweet Dreams (Are Made of This)','Eurythmics','Sweet Dreams (Are Made of This)','1983','Synthpop');